jQuery ->
  if $('#info-div').length>0
    infoDiv = $('#info-div')
    splineContainerName = infoDiv.data('splinecontainername')
    d3ContainerName = infoDiv.data('d3containername')
    floorContainerName = infoDiv.data('floorcontainername')
    barContainerName = infoDiv.data('barcontainername')
    volumeContainerName =  infoDiv.data('volumecontainername')
    seats3dArray = infoDiv.data('seats3darray')
    seatsFloorArray = infoDiv.data('seatsfloorarray')
    seatsVolumeArray = infoDiv.data('seatsvolumearray')
    # console.log seatsVolumeArray
    freeSeatCount = infoDiv.data('freeseatcount')
    plot3dZMax = infoDiv.data('plot3dzmax')
    plot3dYMax = infoDiv.data('plot3dymax')
    lat = infoDiv.data('lat')
    lon = infoDiv.data('lon')
    libraryNamesArray = infoDiv.data('librarynamesarray')
    libraryFreeInfoArray = infoDiv.data('libraryfreeinfoarray')
    libraryBusyInfoArray = infoDiv.data('librarybusyinfoarray')
    libraryVolumeArray = infoDiv.data('libraryvolumearray')
    drawSplineChart(splineContainerName, freeSeatCount)
    draw3DScatterGraph(d3ContainerName, seats3dArray, plot3dZMax, plot3dYMax)
    drawFloorChart(floorContainerName, seatsFloorArray)
    drawBarGraph(barContainerName, libraryNamesArray, libraryFreeInfoArray, libraryBusyInfoArray)
    drawVolumeChart(volumeContainerName, seatsVolumeArray)
    google.maps.event.addDomListener window, 'load', initialize(lat, lon)